[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Lordfirespeed"
name = "Augmented_Enhancer"
description = "A mod for Lethal Company that adds additional configuration options to fit the player's preferences."
websiteUrl = "https://github.com/Lordfirespeed/Lethal-Company-Augmented-Enhancer"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
2018-LC_API = "3.2.2"
NotAtomicBomb-TerminalApi = "1.4.0"

[build]
icon = "icons/icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../Enhancer/bin/com.github.lordfirespeed.augmented_enhancer.dll"
target = "com.github.lordfirespeed.augmented_enhancer.dll"

[[build.copy]]
source = "../LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
source = "../Docs/Changelog.md"
target = "CHANGELOG.md"

[publish]
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "mods", "bepinex", "misc", "tools", "clientside", "serverside", ]
