name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  # Prepare environment and build packages
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      
      - name: Install Tools
        run: dotnet tool restore
      
      # Build packages
      - name: Build
        run: dotnet build
      
      # Store the built packages as an artifact 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "dist/*.zip"
