name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  
  # Prepare environment and build packages
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
      
      # Set up .NET environment for the next steps
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      
      # Install the building/publishing capability of Thunderstore CLI
      - name: Install TCLI
        run: dotnet tool install -g tcli
        
      # Add reference to Enhancer.csproj.user (.gitignored)
      - name: Reference Lethal Company assemblies
        run: |
          ./build.sh --target AddLethalCompanyAssembliesPackageReference
      
      # Build packages
      - name: Build
        run: |
          ./build.sh --target BuildThunderstore
      
      # Store the built packages as an artifact 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "dist/*.zip"
